// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Processor
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("avrogen", "1.12.0+8c27801dc8d42ccc00997f25c0b8f45f8d4a233e")]
	public partial class StorageTemperatureChanged : global::Avro.Specific.ISpecificRecord
	{
		public static global::Avro.Schema _SCHEMA = global::Avro.Schema.Parse("{\"type\":\"record\",\"name\":\"StorageTemperatureChanged\",\"namespace\":\"Processor\",\"fiel" +
				"ds\":[{\"name\":\"Current\",\"type\":\"double\"},{\"name\":\"Published\",\"type\":{\"type\":\"int\"" +
				",\"logicalType\":\"date\"}}]}");
		private double _Current;
		private System.DateTime _Published;
		public virtual global::Avro.Schema Schema
		{
			get
			{
				return StorageTemperatureChanged._SCHEMA;
			}
		}
		public double Current
		{
			get
			{
				return this._Current;
			}
			set
			{
				this._Current = value;
			}
		}
		public System.DateTime Published
		{
			get
			{
				return this._Published;
			}
			set
			{
				this._Published = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Current;
			case 1: return this.Published;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Current = (System.Double)fieldValue; break;
			case 1: this.Published = (System.DateTime)fieldValue; break;
			default: throw new global::Avro.AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
